import "../globals.css";

export const metadata = {
  title: "Projetos | App Galera Das Ondas",
  description: "Generated by create next app",
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({ children }) {
  return (
    <>
      {children}
    </>
  );
}
